#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Sample.Android.Resource", IsApplication=true)]

namespace Sample.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			PullToRefresharp.Resource.Attribute.contentViewId = Sample.Android.Resource.Attribute.contentViewId;
			PullToRefresharp.Resource.Attribute.headerIconDrawable = Sample.Android.Resource.Attribute.headerIconDrawable;
			PullToRefresharp.Resource.Attribute.headerId = Sample.Android.Resource.Attribute.headerId;
			PullToRefresharp.Resource.Attribute.headerTextColor = Sample.Android.Resource.Attribute.headerTextColor;
			PullToRefresharp.Resource.Attribute.ptrHeaderBackground = Sample.Android.Resource.Attribute.ptrHeaderBackground;
			PullToRefresharp.Resource.Attribute.pullDownProgressIndicatorId = Sample.Android.Resource.Attribute.pullDownProgressIndicatorId;
			PullToRefresharp.Resource.Attribute.pullDownTension = Sample.Android.Resource.Attribute.pullDownTension;
			PullToRefresharp.Resource.Attribute.pullEnabled = Sample.Android.Resource.Attribute.pullEnabled;
			PullToRefresharp.Resource.Attribute.pullToRefreshText = Sample.Android.Resource.Attribute.pullToRefreshText;
			PullToRefresharp.Resource.Attribute.refreshingText = Sample.Android.Resource.Attribute.refreshingText;
			PullToRefresharp.Resource.Attribute.releaseToRefreshText = Sample.Android.Resource.Attribute.releaseToRefreshText;
			PullToRefresharp.Resource.Attribute.snapbackDuration = Sample.Android.Resource.Attribute.snapbackDuration;
			PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_end = Sample.Android.Resource.Color.ptrsharp_sb_gradient_end;
			PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_start = Sample.Android.Resource.Color.ptrsharp_sb_gradient_start;
			PullToRefresharp.Resource.Color.ptrsharp_sb_header_text = Sample.Android.Resource.Color.ptrsharp_sb_header_text;
			PullToRefresharp.Resource.Color.ptrsharp_sb_header_text_shadow = Sample.Android.Resource.Color.ptrsharp_sb_header_text_shadow;
			PullToRefresharp.Resource.Drawable.progress_medium_holo = Sample.Android.Resource.Drawable.progress_medium_holo;
			PullToRefresharp.Resource.Drawable.ptrsharp_serious_business_gradient = Sample.Android.Resource.Drawable.ptrsharp_serious_business_gradient;
			PullToRefresharp.Resource.Drawable.serious_business_arrow = Sample.Android.Resource.Drawable.serious_business_arrow;
			PullToRefresharp.Resource.Drawable.serious_business_arrow2 = Sample.Android.Resource.Drawable.serious_business_arrow2;
			PullToRefresharp.Resource.Drawable.spinner_20_inner_holo = Sample.Android.Resource.Drawable.spinner_20_inner_holo;
			PullToRefresharp.Resource.Drawable.spinner_20_outer_holo = Sample.Android.Resource.Drawable.spinner_20_outer_holo;
			PullToRefresharp.Resource.Id.header = Sample.Android.Resource.Id.header;
			PullToRefresharp.Resource.Id.header_container = Sample.Android.Resource.Id.header_container;
			PullToRefresharp.Resource.Id.icon = Sample.Android.Resource.Id.icon;
			PullToRefresharp.Resource.Id.pullDownProgressIndicator = Sample.Android.Resource.Id.pullDownProgressIndicator;
			PullToRefresharp.Resource.Id.text = Sample.Android.Resource.Id.text;
			PullToRefresharp.Resource.Layout.ptrsharp_header = Sample.Android.Resource.Layout.ptrsharp_header;
			PullToRefresharp.Resource.String.library_name = Sample.Android.Resource.String.library_name;
			PullToRefresharp.Resource.String.ptrsharp_pull_to_refresh = Sample.Android.Resource.String.ptrsharp_pull_to_refresh;
			PullToRefresharp.Resource.String.ptrsharp_refreshing = Sample.Android.Resource.String.ptrsharp_refreshing;
			PullToRefresharp.Resource.String.ptrsharp_release_to_refresh = Sample.Android.Resource.String.ptrsharp_release_to_refresh;
			PullToRefresharp.Resource.Style.HoloProgressMedium = Sample.Android.Resource.Style.HoloProgressMedium;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper = Sample.Android.Resource.Styleable.PullToRefresharpWrapper;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_contentViewId = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_contentViewId;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerId = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_headerId;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerTextColor = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_headerTextColor;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownTension = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_pullDownTension;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullEnabled = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_pullEnabled;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_refreshingText = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_refreshingText;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText;
			PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration = Sample.Android.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int contentViewId = 2130771969;
			
			// aapt resource value: 0x7f01000a
			public const int headerIconDrawable = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int headerId = 2130771968;
			
			// aapt resource value: 0x7f010009
			public const int headerTextColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int ptrHeaderBackground = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int pullDownProgressIndicatorId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int pullDownTension = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int pullEnabled = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int pullToRefreshText = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int refreshingText = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int releaseToRefreshText = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int snapbackDuration = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int content_background = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int ptrsharp_sb_gradient_end = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ptrsharp_sb_gradient_start = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ptrsharp_sb_header_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ptrsharp_sb_header_text_shadow = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int nav_width = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android_flavors = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int progress_medium_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ptrsharp_serious_business_gradient = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int rounded_rect = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int serious_business_arrow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int serious_business_arrow2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int spinner_20_inner_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int spinner_20_outer_holo = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int fragment_container = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int gridview = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int header = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int header_container = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int icon = 2131230728;
			
			// aapt resource value: 0x7f080002
			public const int image_view = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int ptr_wrapper = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int pullDownProgressIndicator = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int scrollview = 2131230721;
			
			// aapt resource value: 0x7f080009
			public const int text = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int grid = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int grid_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int image = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int nav = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int nav_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ptrsharp_header = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int app_name = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ptrsharp_pull_to_refresh = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ptrsharp_refreshing = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int ptrsharp_release_to_refresh = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int HoloProgressMedium = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefresharpWrapper = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int PullToRefresharpWrapper_contentViewId = 1;
			
			// aapt resource value: 10
			public const int PullToRefresharpWrapper_headerIconDrawable = 10;
			
			// aapt resource value: 0
			public const int PullToRefresharpWrapper_headerId = 0;
			
			// aapt resource value: 9
			public const int PullToRefresharpWrapper_headerTextColor = 9;
			
			// aapt resource value: 8
			public const int PullToRefresharpWrapper_ptrHeaderBackground = 8;
			
			// aapt resource value: 2
			public const int PullToRefresharpWrapper_pullDownProgressIndicatorId = 2;
			
			// aapt resource value: 4
			public const int PullToRefresharpWrapper_pullDownTension = 4;
			
			// aapt resource value: 11
			public const int PullToRefresharpWrapper_pullEnabled = 11;
			
			// aapt resource value: 5
			public const int PullToRefresharpWrapper_pullToRefreshText = 5;
			
			// aapt resource value: 7
			public const int PullToRefresharpWrapper_refreshingText = 7;
			
			// aapt resource value: 6
			public const int PullToRefresharpWrapper_releaseToRefreshText = 6;
			
			// aapt resource value: 3
			public const int PullToRefresharpWrapper_snapbackDuration = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
