#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SimpleDBSample.Droid.Resource", IsApplication=true)]

namespace SimpleDBSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int ab_background = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ab_bottom_shadow_1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int ab_bottom_shadow_2 = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int action_bar_title_color = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int main_background = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int xam_blue = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int xam_dark_blue = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int xam_gray = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int xam_green = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int xam_light_gray = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int xam_purple = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int discrete_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Ic_action_new_label = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int ListView = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int New = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int Refresher = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int TextView = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int MainMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int New = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int XamActionBarStyle = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int XamActionBarTheme = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int XamActionBarTitleStyle = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
