require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "SimpleDBPersistence-1.0.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="Simple DB Persistence" \
		--summary="Use Amazons Simple DB database as persistence framework." \
		--publisher="Eazy IT" \
		--website="http://eazyit.dk/" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/SimpleDBPersistence_128x128.png" \
		--icon="icons/SimpleDBPersistence_512x512.png" \
		--library="mobile":"bin/Newtonsoft.Json.dll" \
		--library="mobile":"bin/SimpleDBPersistence.dll" \
		--sample="iOS Sample. Demonstrates SimpleDB on iOS.":"samples/SimpleDBSample/SimpleDBSample.sln" \
		--sample="Android Sample. Demonstrates SimpleDB on Android.":"samples/SimpleDBSample/SimpleDBSample.sln" \

		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
